import 'package:esports_battlefield_arena/models/tournament.dart';
import 'package:esports_battlefield_arena/utils/enum.dart';
import 'package:stacked/stacked.dart';

class RegisterTournamentViewModel extends BaseViewModel {
  final List<Tournament> _registeredTournamentList = [
    Tournament(
      tournamentId: '1',
      title: 'Apex Legend 1',
      description:
          'Apex Legend 1 is a first-person shooter video game developed by EA DICE and published by Electronic Arts. It is the fifteenth installment in the Battlefield series, and the first main entry in the series since Battlefield 4.',
      prizePool: 1000,
      startDate: '2021-01-01',
      endDate: '2021-01-03',
      currentParticipant: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      maxParticipants: 14,
      organizerId: 'User 1',
      isSolo: true,
      rules: [
        'Hate speech, offensive behavior, or verbal abuse related to sex, gender identity and expression, sexual orientation, race, ethnicity, disability, physical appearance, body size, age, or religion.',
        'Stalking or intimidation (physically or online).',
        'Spamming, raiding, hijacking, or inciting disruption of streams or social media',
        'Posting or threatening to post other people’s personally identifying information (“doxing”)',
        'Unwelcome sexual attention. This includes, unwelcome sexualized comments, jokes, and sexual advances.',
        'Advocating for, or encouraging, any of the above behavior.',
        'Penalty Points & barrages are given for incidents within ESL-Matches',
        'Exclusion of the offending player from the current tournaments in which they are participating*',
        'Insults or inappropriate behaviour within Comments or other options for contacting a player, will result in a Forum- & Comment ban',
        'Rule 10',
      ],
      game: GameType.ApexLegend.name,
      status: GameStatus.pending.name,
      maxMemberPerTeam: 0,
    ),
    Tournament(
      tournamentId: '2',
      title: 'Valorant',
      description:
          'Valorant is a free-to-play multiplayer first-person shooter developed and published by Riot Games. Set in the near future, players control one of a number of agents, each with their own unique set of abilities.',
      prizePool: 5000,
      startDate: '2023-05-01',
      endDate: '2023-05-03',
      currentParticipant: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      maxParticipants: 12,
      organizerId: 'User 2',
      isSolo: false,
      rules: [
        'Hate speech, offensive behavior, or verbal abuse related to sex, gender identity and expression, sexual orientation, race, ethnicity, disability, physical appearance, body size, age, or religion.',
        'Stalking or intimidation (physically or online).',
        'Spamming, raiding, hijacking, or inciting disruption of streams or social media',
        'Posting or threatening to post other people’s personally identifying information (“doxing”)',
        'Unwelcome sexual attention. This includes, unwelcome sexualized comments, jokes, and sexual advances.',
        'Advocating for, or encouraging, any of the above behavior.',
        'Penalty Points & barrages are given for incidents within ESL-Matches',
        'Exclusion of the offending player from the current tournaments in which they are participating*',
        'Insults or inappropriate behaviour within Comments or other options for contacting a player, will result in a Forum- & Comment ban',
        'Rule 10',
      ],
      game: GameType.Valorant.name,
      status: GameStatus.ongoing.name,
      maxMemberPerTeam: 5,
    ),
    Tournament(
      tournamentId: '1',
      title:
          'Apex Legend 1 dasdawd dawdaw dawdawtgae we wedwa dawf awrf dsa dwsad wadaw',
      description:
          'Apex Legend 1 is a first-person shooter video game developed by EA DICE and published by Electronic Arts. It is the fifteenth installment in the Battlefield series, and the first main entry in the series since Battlefield 4.',
      prizePool: 1000,
      startDate: '2021-01-01',
      endDate: '2021-01-03',
      currentParticipant: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      maxParticipants: 14,
      organizerId: 'User 1',
      isSolo: true,
      game: GameType.ApexLegend.name,
      maxMemberPerTeam: 0,
      rules: [
        'Hate speech, offensive behavior, or verbal abuse related to sex, gender identity and expression, sexual orientation, race, ethnicity, disability, physical appearance, body size, age, or religion.',
        'Stalking or intimidation (physically or online).',
        'Spamming, raiding, hijacking, or inciting disruption of streams or social media',
        'Posting or threatening to post other people’s personally identifying information (“doxing”)',
        'Unwelcome sexual attention. This includes, unwelcome sexualized comments, jokes, and sexual advances.',
        'Advocating for, or encouraging, any of the above behavior.',
        'Penalty Points & barrages are given for incidents within ESL-Matches',
        'Exclusion of the offending player from the current tournaments in which they are participating*',
        'Insults or inappropriate behaviour within Comments or other options for contacting a player, will result in a Forum- & Comment ban',
        'Rule 10',
      ],
    ),
    Tournament(
      tournamentId: '2',
      title: 'Valorant',
      description:
          'Valorant is a free-to-play multiplayer first-person shooter developed and published by Riot Games. Set in the near future, players control one of a number of agents, each with their own unique set of abilities.',
      prizePool: 5000,
      startDate: '2023-05-01',
      endDate: '2023-05-03',
      currentParticipant: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      maxParticipants: 12,
      organizerId: 'User 2',
      isSolo: false,
      game: GameType.Valorant.name,
      status: GameStatus.completed.name,
      maxMemberPerTeam: 5,
      rules: [
        'Hate speech, offensive behavior, or verbal abuse related to sex, gender identity and expression, sexual orientation, race, ethnicity, disability, physical appearance, body size, age, or religion.',
        'Stalking or intimidation (physically or online).',
        'Spamming, raiding, hijacking, or inciting disruption of streams or social media',
        'Posting or threatening to post other people’s personally identifying information (“doxing”)',
        'Unwelcome sexual attention. This includes, unwelcome sexualized comments, jokes, and sexual advances.',
        'Advocating for, or encouraging, any of the above behavior.',
        'Penalty Points & barrages are given for incidents within ESL-Matches',
        'Exclusion of the offending player from the current tournaments in which they are participating*',
        'Insults or inappropriate behaviour within Comments or other options for contacting a player, will result in a Forum- & Comment ban',
        'Rule 10',
      ],
    ),
    Tournament(
      tournamentId: '1',
      title: 'Apex Legend 1',
      description:
          'Apex Legend 1 is a first-person shooter video game developed by EA DICE and published by Electronic Arts. It is the fifteenth installment in the Battlefield series, and the first main entry in the series since Battlefield 4.',
      prizePool: 1000,
      startDate: '2021-01-01',
      endDate: '2021-01-03',
      currentParticipant: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      maxParticipants: 14,
      organizerId: 'User 1',
      isSolo: true,
      game: GameType.ApexLegend.name,
      status: GameStatus.completed.name,
      maxMemberPerTeam: 0,
      rules: [
        'Hate speech, offensive behavior, or verbal abuse related to sex, gender identity and expression, sexual orientation, race, ethnicity, disability, physical appearance, body size, age, or religion.',
        'Stalking or intimidation (physically or online).',
        'Spamming, raiding, hijacking, or inciting disruption of streams or social media',
        'Posting or threatening to post other people’s personally identifying information (“doxing”)',
        'Unwelcome sexual attention. This includes, unwelcome sexualized comments, jokes, and sexual advances.',
        'Advocating for, or encouraging, any of the above behavior.',
        'Penalty Points & barrages are given for incidents within ESL-Matches',
        'Exclusion of the offending player from the current tournaments in which they are participating*',
        'Insults or inappropriate behaviour within Comments or other options for contacting a player, will result in a Forum- & Comment ban',
        'Rule 10',
      ],
    ),
    Tournament(
      tournamentId: '2',
      title: 'Valorant',
      description:
          'Valorant is a free-to-play multiplayer first-person shooter developed and published by Riot Games. Set in the near future, players control one of a number of agents, each with their own unique set of abilities.',
      prizePool: 5000,
      startDate: '2023-05-01',
      endDate: '2023-05-03',
      currentParticipant: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      maxParticipants: 12,
      organizerId: 'User 2',
      isSolo: false,
      game: GameType.Valorant.name,
      status: GameStatus.completed.name,
      maxMemberPerTeam: 5,
      rules: [
        'Hate speech, offensive behavior, or verbal abuse related to sex, gender identity and expression, sexual orientation, race, ethnicity, disability, physical appearance, body size, age, or religion.',
        'Stalking or intimidation (physically or online).',
        'Spamming, raiding, hijacking, or inciting disruption of streams or social media',
        'Posting or threatening to post other people’s personally identifying information (“doxing”)',
        'Unwelcome sexual attention. This includes, unwelcome sexualized comments, jokes, and sexual advances.',
        'Advocating for, or encouraging, any of the above behavior.',
        'Penalty Points & barrages are given for incidents within ESL-Matches',
        'Exclusion of the offending player from the current tournaments in which they are participating*',
        'Insults or inappropriate behaviour within Comments or other options for contacting a player, will result in a Forum- & Comment ban',
        'Rule 10',
      ],
    ),
    Tournament(
      tournamentId: '1',
      title: 'Apex Legend 1 dasd wd asd wadswadsa edwadwad',
      description:
          'Apex Legend 1 is a first-person shooter video game developed by EA DICE and published by Electronic Arts. It is the fifteenth installment in the Battlefield series, and the first main entry in the series since Battlefield 4.',
      prizePool: 1000,
      startDate: '2021-01-01',
      endDate: '2021-01-03',
      currentParticipant: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      maxParticipants: 14,
      organizerId: 'User 1',
      isSolo: true,
      game: GameType.ApexLegend.name,
      status: GameStatus.completed.name,
      maxMemberPerTeam: 0,
      rules: [
        'Hate speech, offensive behavior, or verbal abuse related to sex, gender identity and expression, sexual orientation, race, ethnicity, disability, physical appearance, body size, age, or religion.',
        'Stalking or intimidation (physically or online).',
        'Spamming, raiding, hijacking, or inciting disruption of streams or social media',
        'Posting or threatening to post other people’s personally identifying information (“doxing”)',
        'Unwelcome sexual attention. This includes, unwelcome sexualized comments, jokes, and sexual advances.',
        'Advocating for, or encouraging, any of the above behavior.',
        'Penalty Points & barrages are given for incidents within ESL-Matches',
        'Exclusion of the offending player from the current tournaments in which they are participating*',
        'Insults or inappropriate behaviour within Comments or other options for contacting a player, will result in a Forum- & Comment ban',
        'Rule 10',
      ],
    ),
    Tournament(
      tournamentId: '2',
      title: 'Valorant',
      description:
          'Valorant is a free-to-play multiplayer first-person shooter developed and published by Riot Games. Set in the near future, players control one of a number of agents, each with their own unique set of abilities.',
      prizePool: 5000,
      startDate: '2023-05-01',
      endDate: '2023-05-03',
      maxParticipants: 12,
      organizerId: 'User 2',
      isSolo: false,
      game: GameType.Valorant.name,
      status: GameStatus.completed.name,
      maxMemberPerTeam: 5,
      rules: [
        'Hate speech, offensive behavior, or verbal abuse related to sex, gender identity and expression, sexual orientation, race, ethnicity, disability, physical appearance, body size, age, or religion.',
        'Stalking or intimidation (physically or online).',
        'Spamming, raiding, hijacking, or inciting disruption of streams or social media',
        'Posting or threatening to post other people’s personally identifying information (“doxing”)',
        'Unwelcome sexual attention. This includes, unwelcome sexualized comments, jokes, and sexual advances.',
        'Advocating for, or encouraging, any of the above behavior.',
        'Penalty Points & barrages are given for incidents within ESL-Matches',
        'Exclusion of the offending player from the current tournaments in which they are participating*',
        'Insults or inappropriate behaviour within Comments or other options for contacting a player, will result in a Forum- & Comment ban',
        'Rule 10',
      ],
    )
  ];

  //TODO: a function that help to decide whether tournament is finish or not
  isTournamentFinished(Tournament tournament) {
    return false;
  }

  List<Tournament> get registeredTournamentList => _registeredTournamentList;

  Future<void> refreshRegisteredTournament() {
    return Future.delayed(const Duration(seconds: 2));
  }
}
